# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('lat_long', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(verbose_name='date published')),
                ('num_critical_violations', models.IntegerField(default=0)),
                ('num_uncorrected_critical_violations', models.IntegerField(default=0)),
                ('inspection_comments', models.CharField(max_length=500)),
                ('violation_descriptions', models.CharField(max_length=500)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Facility')),
            ],
        ),
    ]
