# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_facility_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='inspection_date',
            field=models.DateField(),
        ),
    ]
