# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20170922_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
