# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20170922_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='violation_descriptions',
            new_name='violation_description',
        ),
    ]
