git rm -f ./foodviolations/__init__.pyc
git rm -f ./foodviolations/settings.pyc
git rm -f ./foodviolations/urls.pyc
git rm -f ./foodviolations/wsgi.pyc
git rm -f ./restaurants/__init__.pyc
git rm -f ./restaurants/admin.pyc
git rm -f ./restaurants/apps.pyc
git rm -f ./restaurants/migrations/0001_initial.pyc
git rm -f ./restaurants/migrations/0002_facility_county.pyc
git rm -f ./restaurants/migrations/0003_auto_20170922_0549.pyc
git rm -f ./restaurants/migrations/0004_auto_20170922_0603.pyc
git rm -f ./restaurants/migrations/0005_auto_20170922_0643.pyc
git rm -f ./restaurants/migrations/__init__.pyc
git rm -f ./restaurants/models.pyc
git rm -f ./restaurants/urls.pyc
git rm -f ./restaurants/views.pyc
